# This file was generated by GoReleaser. DO NOT EDIT.
class Nvls < Formula
  desc "Check availability of potential names for software projects"
  homepage "https://nvls.sh"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/craftyphotons/nvls/releases/download/v0.1.0/nvls-0.1.0-macOS-x86_64.tar.gz"
    sha256 "52b7cfb883b553a64ea0b8d5ad48dd42a2b94e00b11abbb05f422afa518dc4e6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/craftyphotons/nvls/releases/download/v0.1.0/nvls-0.1.0-Linux-x86_64.tar.gz"
      sha256 "c369db74599b0fb9943157b66bbd6d5d33e47922bb6f935859b2c27247902686"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/craftyphotons/nvls/releases/download/v0.1.0/nvls-0.1.0-Linux-arm64.tar.gz"
        sha256 "686cf705f936058cb5ecec216861324007c7e7b78384adc63d7592bcd49bb050"
      else
      end
    end
  end
  
  head do
    url "https://github.com/craftyphotons/nvls.git"
    depends_on "go"
  end

  def install
    system "make" if build.head?
    bin.install "bin/nvls"
    (bash_completion/"nvls.sh").write `#{bin}/nvls completion bash`
    (zsh_completion/"_nvls").write `#{bin}/nvls completion zsh`
    (fish_completion/"nvls.fish").write `#{bin}/nvls completion fish`
  end

  test do
    help_text = shell_output("#{bin}/nvls --help")
    assert_includes help_text, "Usage:"
  end
end
